name: Sync Weblate Commits

on:
  push:
    branches:
      - main

jobs:
  check-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/racicLuka/weblate-test.git
          cd weblate-test
          git checkout main
      - name: List Weblate Commits
        id: weblate-commits
        run: |
          cd weblate-test
          git fetch origin
          COMMITS=$(git log --grep="Weblate" main --format=%H)
          echo "these are the commits $COMMITS"
          BR=$(git branch -a)
          echo "there are the branches $BR"
          