name: Sync Weblate Commits

on:
  push:
    branches:
      - main

jobs:
  check-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/racicLuka/weblate-test.git
          cd weblate-test
          git checkout main
      - name: List Weblate Commits
        id: weblate-commits
        run: |
          git fetch origin
          git branch --show-current
          git log
          git log --grep="Weblate" main
          git log --grep="Weblate" origin/main
          git log --grep="Weblate" remotes/origin/main
          BR=$(git branch -a)
          echo "there are the branches $BR"
          